package es.jarroyo.daggerandkotlin.data.exception


class UserAlreadyExistsException : Exception()
